name: turque
#prefix: /your/custom/path/envs/turque
channels:
  - anaconda
dependencies:
  - anaconda::cudatoolkit=11
  - pip
  - python=3.8
  - pytorch::pytorch
  - pip:
    - bert-score>=0.3.10
    - black==21.7b0
    - datasets>=1.12.0
    - flake8==3.9.2
    - gdown
    - isort==5.9.2
    - jupyterlab==3.0.14
    - jury>=1.1.1
    - protobuf>=3.17.3
    - pyyaml
    - pysocks==1.5.6
    - rouge-score==0.0.4
    - sacrebleu==1.5.1
    - sentencepiece
    - transformers>=4.10.0
    - trtokenizer>=0.0.3
