model_name_or_path: "dbmdz/bert-base-turkish-cased"
tokenizer_path: "tokenizers/bert-base-turkish-cased_tokenizer"
label_smoothing: 0
freeze_embeddings: false
run_name: "turque-bertbase-adamw-1e4-3ep-tquad2train"
wandb_project: null
wandb_id: null
neptune_project: null
neptune_run: null
neptune_api_token:
train_dataset_list: ["tquad2-train"]
valid_dataset_list: ["tquad2-valid"]
eval_dataset_list: ["tquad2-valid", "xquad.tr"]
train_file_path: "data/train_data.pt"
valid_file_path: "data/valid_data.pt"
max_source_length: 512
max_target_length: 64
prepare_data: true
output_dir: "runs/bert-base/turque-bertbase-adamw-1e4-3ep-tquad2train"
do_train: true
do_eval: true
evaluation_strategy: "steps"
eval_steps: 300
logging_steps: 300
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
gradient_accumulation_steps: 1
eval_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3
save_total_limit: 1
no_cuda: false
seed: 42
fp16: false
fp16_full_eval: false
adafactor: false